project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Floyd Everest
    right:
      - href: mailto:me@floydeverest.com
        icon: envelope-fill
      - href: https://github.com/fleverest
        icon: github

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



