on:
  push:
    branches: main

name: Publish website

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site